#!/usr/bin/env bash
# This script displays "Best School" 10 times, with a special case for the 9th iteration.

# Initialize a counter
counter=0

# Using a while loop to repeat the message 10 times
while [ $counter -lt 10 ]
do
    # Check if it's the 9th iteration
    if [ $counter -eq 8 ]
    then
        echo -e "Best School\nHi"
    else
        echo "Best School"
    fi
    
    # Increment the counter
    ((counter++))
done
